server:
  port: 8085

spring:

  cloud:
    gateway:
      routes:
        - id: consultation-service
          uri: http://localhost:8090
          predicates:
            - Path=/consultation/**
          filters:
            - RewritePath=/consultation(?<segment>/?.*), $\{segment}
        - id: authentication-service
          uri: http://localhost:3306
          predicates:
            - Path=/authentication/**
          filters:
            - RewritePath=/authentication(?<segment>/?.*), $\{segment}

        - id: email-service
          uri: http://localhost:8075
          predicates:
            - Path=/email/**
          filters:
            - RewritePath=/email(?<segment>/?.*), $\{segment}

        - id: payment-service
          uri: http://localhost:8072
          predicates:
            - Path=/payment/**
          filters:
            - RewritePath=/payment(?<segment>/?.*), $\{segment}

        - id: pharmacy-service
          uri: http://localhost:9000
          predicates:
            - Path=/pharmacy/**
          filters:
            - RewritePath=/pharmacy(?<segment>/?.*), $\{segment}
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user(?<segment>/?.*), $\{segment}

        - id: chat-service
          uri: http://localhost:9090
          predicates:
            - Path=/chat/**
          filters:
            - RewritePath=/chat(?<segment>/?.*), $\{segment}

        - id: technical-support-service
          uri: http://localhost:8081
          predicates:
            - Path=/technical-support/**
          filters:
            - RewritePath=/technical-support(?<segment>/?.*), $\{segment}

